# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d4a8467bd2298b0fef6a3d7e986f7868912380cde1a29a22b6b2a88c960c8df645b871e7883f643bd8a5ad353b9fad9b82656a1bfc153482aa5b4fecb91fffc

test:
  secret_key_base: 90e1c7b588d84eefed88150696918eac5dafb6c805f8aa0687cb07eca9946b4c9cf29bedc257b1ccfd2422bbb044b5400f1b27b9be93faba2a4f81fcca0ed671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
